workflows:
  expo-build:
    name: Expo Build Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN:
          value: $EXPO_TOKEN
      node: 20
      flutter: none
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Login to Expo
        script: |
          echo $EXPO_TOKEN | expo login --token
      - name: Build Expo app
        script: |
          # For iOS IPA
          expo build:ios --non-interactive --no-wait
          # For Android APK
          expo build:android --non-interactive --no-wait
    artifacts:
      - build/**/*.ipa
      - build/**/*.apk
      - build/**/*.aab
