workflows:
  expo-workflow:
    name: Expo Build Workflow
    environment:
      groups:
        - expo-secrets 
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Login to Expo
        script: |
          echo $EXPO_TOKEN | eas login --token
      - name: Build iOS IPA
        script: |
          eas build --platform ios --non-interactive --profile production
      - name: Build Android APK
        script: |
          eas build --platform android --non-interactive --profile production
    artifacts:
      - build/**/*.ipa
      - build/**/*.apk
      - build/**/*.aab
